package stream.flarebot.flarebot;

public enum Language {

    // General
    GENERAL_INVALIDARGUMENT,
    GENERAL_USAGE,
    GENERAL_SUCCESS,
    GENERAL_USER,
    // Auto Assign
    AUTOASSIGN_CURRENT,
    AUTOASSIGN_NOROLES,
    AUTOASSIGN_INVALIDROLE,
    AUTOASSIGN_ADDASSIGNED,
    AUTOASSIGN_REMOVEASSIGNED,
    AUTOASSIGN_ALREADYASSIGNED,
    AUTOASSIGN_NOTAUTOASSIGNROLE,
    AUTOASSIGN_DESCRIPTION,
    AUTOASSIGN_USAGE,
    // Ban
    BAN_USERNOTFOUND,
    BAN_BANHAMMERSTRUCK,
    BAN_CANTBAN,
    BAN_DESCRIPTION,
    BAN_USAGE,
    // Permissions
    PERMISSIONS_USERNOEXIST,
    PERMISSIONS_GROUPNOEXIST,
    PERMISSIONS_USERHADGROUP,
    PERMISSIONS_USERNEVERHADGROUP,
    PERMISSIONS_GROUPS,
    PERMISSIONS_GROUPHADPERM,
    PERMISSIONS_GROUPNEVERHADPERM,
    PERMISSIONS_PERMSFORGROUP,
    PERMISSIONS_COULDNOTSAVE,
    PERMISSIONS_DESCRIPTION,
    PERMISSIONS_USAGE,
    // Pin
    PIN_DESCRIPTION,
    PIN_USAGE,
    // Purge
    PURGE_COOLDOWN,
    PURGE_MIN,
    PURGE_DELETED,
    PURGE_FAILED,
    PURGE_NOPERMS,
    PURGE_DESCRIPTION,
    PURGE_USAGE,
    // Roles
    ROLES_SERVERROLES,
    ROLES_DESCRIPTION,
    ROLES_USAGE,
    // Prefix
    PREFIX_TOOLONG,
    PREFIX_SETPREFIX,
    PREFIX_CURRENT,
    PREFIX_DESCRIPTION,
    PREFIX_USAGE,
    // Welcomes
    WELCOMES_ENABLED,
    WELCOMES_ALREADYENABLED,
    WELCOMES_DISABLED,
    WELCOMES_ALREADYDISABLED,
    WELCOMES_APPEARSET,
    WELCOMES_NOTENABLED,
    WELCOMES_SETHELP,
    WELCOMES_CURRENTMESSAGE,
    WELCOMES_SET,
    WELCOMES_DESCRIPTION,
    WELCOMES_USAGE,
    // Automod
    //TODO: To be done once feature is ready for prod
    // Help
    HELP_NOSUCHCATEGORY,
    HELP_HEADER,
    HELP_CONTINUED,
    HELP_DESCRIPTION,
    // Info
    INFO_HEADER,
    INFO_INFONOTFOUND,
    INFO_DESCRIPTION,
    INFO_USAGE,
    INFO_CONTENT_SERVERS,
    INFO_CONTENT_TOTALUSERS,
    INFO_CONTENT_VOICECONNECTIONS,
    INFO_CONTENT_MUSICCHANNELS,
    INFO_CONTENT_TEXTCHANNELS,
    INFO_CONTENT_UPTIME,
    INFO_CONTENT_MEMUSAGE,
    INFO_CONTENT_MEMFREE,
    INFO_CONTENT_VIDTHREADS,
    INFO_CONTENT_TOTALTHREADS,
    INFO_CONTENT_VERSION,
    INFO_CONTENT_JDAVERSION,
    INFO_CONTENT_GITREVISION,
    INFO_CONTENT_SUPPORTSERVER,
    INFO_CONTENT_DONATE,
    INFO_CONTENT_OURPATREON,
    INFO_CONTENT_PATREON,
    INFO_CONTENT_WEBSITE,
    INFO_CONTENT_TWITTER,
    INFO_CONTENT_INVITE,
    INFO_CONTENT_MADEBY,
    INFO_CONTENT_MADEBYCONTENT,
    INFO_CONTENT_SOURCE;


    public enum Locales {

        ENGLISH_UK("en_uk"),
        ENGLISH_US("en_us"),
        FRENCH("fr");

        private String code;

        Locales(String code) {
            this.code = code;
        }

        public static Locales from(String s) {
            for (Locales l : Locales.values()) {
                if (s.equalsIgnoreCase(l.getCode()))
                    return l;
            }
            throw new IllegalArgumentException("Unknown language code (" + s + ") !");
        }

        public String getCode() {
            return code;
        }
    }
}
