package stream.flarebot.flarebot;

/**
 * Created by William on 03/05/2017.
 * Project flarebot
 */
public enum Language {

    // General
    GENERAL_INVALIDARGUMENT,
    GENERAL_USAGE,
    GENERAL_SUCCESS,
    GENERAL_USER,
    // Auto Assign
    AUTOASSIGN_CURRENT,
    AUTOASSIGN_NOROLES,
    AUTOASSIGN_INVALIDROLE,
    AUTOASSIGN_ADDASSIGNED,
    AUTOASSIGN_REMOVEASSIGNED,
    AUTOASSIGN_ALREADYASSIGNED,
    AUTOASSIGN_NOTAUTOASSIGNROLE,
    AUTOASSIGN_DESCRIPTION,
    // Permissions
    PERMISSIONS_USERNOEXIST,
    PERMISSIONS_GROUPNOEXIST,
    PERMISSIONS_USERHADGROUP,
    PERMISSIONS_USERNEVERHADGROUP,
    PERMISSIONS_GROUPS,
    PERMISSIONS_GROUPHADPERM,
    PERMISSIONS_GROUPNEVERHADPERM,
    PERMISSIONS_PERMSFORGROUP,
    PERMISSIONS_COULDNOTSAVE,
    PERMISSIONS_DESCRIPTION,
    // Pin
    PIN_DESCRIPTION,
    PIN_USAGE,
    // Purge
    PURGE_COOLDOWN,
    PURGE_MIN,
    PURGE_DELETED,
    PURGE_FAILED,
    PURGE_NOPERMS,
    PURGE_DESCRIPTION,








}
